language: go

sudo: false
services:
  - mongodb

go:
 - 1.4
 - tip

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

install:
 - wget https://raw.githubusercontent.com/tidepool-org/tools/master/come_deps.sh
 - chmod -R 777 ./come_deps.sh
 - export PATH=$PATH:$PWD

script:
 - source ./build
 - go test -v

