sudo: false

language: go

go:
  - 1.9.2

addons:
  apt:
    sources:
      - mongodb-3.2-trusty
    packages:
      - mongodb-org-server
  artifacts:
    s3_region: us-west-2
    paths:
      - $(git ls-files -o deploy/*/*-*.tar.gz | tr "\n" ":")
    target_paths:
      - /

services:
  - docker
  - mongodb

script:
  - ./build.sh
  - ./test.sh
  - ./artifact.sh
