// Code generated by mockery v2.12.3. DO NOT EDIT.

package usecase

import (
	bytes "bytes"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUploader is an autogenerated mock type for the Uploader type
type MockUploader struct {
	mock.Mock
}

type MockUploader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploader) EXPECT() *MockUploader_Expecter {
	return &MockUploader_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: ctx, filename, buffer
func (_m *MockUploader) Upload(ctx context.Context, filename string, buffer *bytes.Buffer) error {
	ret := _m.Called(ctx, filename, buffer)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *bytes.Buffer) error); ok {
		r0 = rf(ctx, filename, buffer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUploader_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockUploader_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//  - ctx context.Context
//  - filename string
//  - buffer *bytes.Buffer
func (_e *MockUploader_Expecter) Upload(ctx interface{}, filename interface{}, buffer interface{}) *MockUploader_Upload_Call {
	return &MockUploader_Upload_Call{Call: _e.mock.On("Upload", ctx, filename, buffer)}
}

func (_c *MockUploader_Upload_Call) Run(run func(ctx context.Context, filename string, buffer *bytes.Buffer)) *MockUploader_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*bytes.Buffer))
	})
	return _c
}

func (_c *MockUploader_Upload_Call) Return(_a0 error) *MockUploader_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

type NewMockUploaderT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockUploader creates a new instance of MockUploader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockUploader(t NewMockUploaderT) *MockUploader {
	mock := &MockUploader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
