// Code generated by mockery v2.12.3. DO NOT EDIT.

package usecase

import (
	mock "github.com/stretchr/testify/mock"
	common "github.com/tidepool-org/tide-whisperer/common"
)

// MockPatientDataUseCase is an autogenerated mock type for the PatientDataUseCase type
type MockPatientDataUseCase struct {
	mock.Mock
}

type MockPatientDataUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPatientDataUseCase) EXPECT() *MockPatientDataUseCase_Expecter {
	return &MockPatientDataUseCase_Expecter{mock: &_m.Mock}
}

// GetData provides a mock function with given fields: args
func (_m *MockPatientDataUseCase) GetData(args GetDataArgs) *common.DetailedError {
	ret := _m.Called(args)

	var r0 *common.DetailedError
	if rf, ok := ret.Get(0).(func(GetDataArgs) *common.DetailedError); ok {
		r0 = rf(args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*common.DetailedError)
		}
	}

	return r0
}

// MockPatientDataUseCase_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type MockPatientDataUseCase_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
//  - args GetDataArgs
func (_e *MockPatientDataUseCase_Expecter) GetData(args interface{}) *MockPatientDataUseCase_GetData_Call {
	return &MockPatientDataUseCase_GetData_Call{Call: _e.mock.On("GetData", args)}
}

func (_c *MockPatientDataUseCase_GetData_Call) Run(run func(args GetDataArgs)) *MockPatientDataUseCase_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(GetDataArgs))
	})
	return _c
}

func (_c *MockPatientDataUseCase_GetData_Call) Return(_a0 *common.DetailedError) *MockPatientDataUseCase_GetData_Call {
	_c.Call.Return(_a0)
	return _c
}

type NewMockPatientDataUseCaseT interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockPatientDataUseCase creates a new instance of MockPatientDataUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockPatientDataUseCase(t NewMockPatientDataUseCaseT) *MockPatientDataUseCase {
	mock := &MockPatientDataUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
