// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// varsHandler is an autogenerated mock type for the varsHandler type
type varsHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *varsHandler) Execute(_a0 http.ResponseWriter, _a1 *http.Request, _a2 map[string]string) {
	_m.Called(_a0, _a1, _a2)
}

type newVarsHandlerT interface {
	mock.TestingT
	Cleanup(func())
}

// newVarsHandler creates a new instance of varsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newVarsHandler(t newVarsHandlerT) *varsHandler {
	mock := &varsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
